### ISSUE TITLE
ModuleNotFoundError: No module named 'cuda_ba'

### ISSUE THREAD

**Issue by programath** [princeton-vl/DPVO_Docker#1]
I tried to build DPVO using docker following the instruction. The installation is smooth but when I ran the command

`(dpvo) root@9f244f8eee53:/DPVO# python demo.py --imagedir /media/movies/IMG_0497.MOV --calib calib/iphone.txt --network /media/dpvo.pth --stride 5 --viz`

it turns out to be:

> 
> Traceback (most recent call last): 
>   File "/DPVO/demo.py", line 10, in <module>
>     from dpvo.dpvo import DPVO
>   File "/DPVO/dpvo/dpvo.py", line 5, in <module>
>     from . import fastba
>   File "/DPVO/dpvo/fastba/__init__.py", line 1, in <module>
>     from .ba import BA, neighbors, reproject
>   File "/DPVO/dpvo/fastba/ba.py", line 2, in <module>
>     import cuda_ba
> ModuleNotFoundError: No module named 'cuda_ba'

Any idea to resolve this problem?

**Comment by lahavlipson** [comment]
Were there any errors when running `./install_dpvo.sh`?

**Comment by programath** [comment]
Yeah, after running install_dpvo.sh the problem was fixed. However, another bug was reported.

```
error: XDG_RUNTIME_DIR not set in the environment.
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.Segmentation fault (core dumped)
```

It seems to be the problem of docker visualization, but I have no idea how to solve it.

**Comment by programath** [comment]
I just fixed it following the instruction of this issue [comment](https://github.com/princeton-vl/DPVO/issues/9#issuecomment-1285238706) and everything goes well now. Thx!
